import { Bike, BikeImage, RentalShop, Review, User } from './types';

// Mock shop data
export const mockShops: RentalShop[] = [
  {
    id: '1',
    owner_id: 'owner1',
    name: 'Cloud 9 Bikes',
    description: 'Premium motorbike rentals right next to Cloud 9 surf spot',
    address: 'Cloud 9, Tourism Road',
    city: 'General Luna',
    latitude: 9.7942,
    longitude: 126.1760,
    phone_number: '+63 939 123 4567',
    whatsapp: '+63 939 123 4567',
    email: 'cloud9bikes@example.com',
    opening_hours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '08:00', close: '18:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    logo_url: 'https://placehold.co/400x400/1e3b8a/white?text=C9+Bikes',
    banner_url: 'https://placehold.co/1200x400/1e3b8a/white?text=Cloud+9+Bikes',
    is_verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    owner_id: 'owner2',
    name: 'Daku Island Rentals',
    description: 'Best prices for long-term rentals in Siargao',
    address: 'Tourism Road, near Daku boat terminal',
    city: 'General Luna',
    latitude: 9.8033,
    longitude: 126.1793,
    phone_number: '+63 939 987 6543',
    whatsapp: '+63 939 987 6543',
    email: 'dakurentals@example.com',
    opening_hours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '07:00', close: '19:00' },
    },
    logo_url: 'https://placehold.co/400x400/3a7a1e/white?text=Daku+Rentals',
    banner_url: 'https://placehold.co/1200x400/3a7a1e/white?text=Daku+Island+Rentals',
    is_verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    owner_id: 'owner3',
    name: 'Siargao Scooters',
    description: 'Affordable scooters and motorbikes for tourists',
    address: 'Main Street, Poblacion',
    city: 'General Luna',
    latitude: 9.8144,
    longitude: 126.1710,
    phone_number: '+63 939 456 7890',
    whatsapp: '+63 939 456 7890',
    email: 'siargaoscooters@example.com',
    logo_url: 'https://placehold.co/400x400/8a1e3b/white?text=Siargao+Scooters',
    banner_url: 'https://placehold.co/1200x400/8a1e3b/white?text=Siargao+Scooters',
    is_verified: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock bike images
export const mockBikeImages: Record<string, BikeImage[]> = {
  'bike1': [
    {
      id: 'img1',
      bike_id: 'bike1',
      image_url: 'https://placehold.co/600x400/1e3b8a/white?text=Honda+Click+125i',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'img2',
      bike_id: 'bike1',
      image_url: 'https://placehold.co/600x400/1e3b8a/white?text=Honda+Click+Side',
      is_primary: false,
      created_at: new Date().toISOString(),
    },
  ],
  'bike2': [
    {
      id: 'img3',
      bike_id: 'bike2',
      image_url: 'https://placehold.co/600x400/3a7a1e/white?text=Yamaha+Mio+125',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
  ],
  'bike3': [
    {
      id: 'img4',
      bike_id: 'bike3',
      image_url: 'https://placehold.co/600x400/8a1e3b/white?text=Honda+XRM+125',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
  ],
  'bike4': [
    {
      id: 'img5',
      bike_id: 'bike4',
      image_url: 'https://placehold.co/600x400/1e3b8a/white?text=Kawasaki+KLX+150',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'img6',
      bike_id: 'bike4',
      image_url: 'https://placehold.co/600x400/1e3b8a/white?text=Kawasaki+KLX+Front',
      is_primary: false,
      created_at: new Date().toISOString(),
    },
  ],
  'bike5': [
    {
      id: 'img7',
      bike_id: 'bike5',
      image_url: 'https://placehold.co/600x400/3a7a1e/white?text=Honda+Beat+115',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
  ],
  'bike6': [
    {
      id: 'img8',
      bike_id: 'bike6',
      image_url: 'https://placehold.co/600x400/8a1e3b/white?text=Suzuki+Raider+150',
      is_primary: true,
      created_at: new Date().toISOString(),
    },
  ],
};

// Mock bike data
export const mockBikes: Bike[] = [
  {
    id: 'bike1',
    shop_id: '1',
    name: 'Honda Click 125i',
    description: 'Reliable automatic scooter, perfect for exploring the island',
    category: 'scooter',
    price_per_day: 400,
    price_per_week: 2500,
    price_per_month: 9000,
    is_available: true,
    specifications: {
      engine: '125cc',
      year: 2022,
      color: 'Blue',
      features: ['Fuel Injection', 'Digital Dashboard', 'USB Port']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike1'],
  },
  {
    id: 'bike2',
    shop_id: '1',
    name: 'Yamaha Mio 125',
    description: 'Smooth riding automatic scooter with good fuel efficiency',
    category: 'scooter',
    price_per_day: 350,
    price_per_week: 2200,
    price_per_month: 8500,
    is_available: true,
    specifications: {
      engine: '125cc',
      year: 2021,
      color: 'Green',
      features: ['Large Storage', 'Light Weight']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike2'],
  },
  {
    id: 'bike3',
    shop_id: '2',
    name: 'Honda XRM 125',
    description: 'Semi-automatic bike, great for rough roads and off-road trails',
    category: 'semi_auto',
    price_per_day: 450,
    price_per_week: 2800,
    price_per_month: 10000,
    is_available: true,
    specifications: {
      engine: '125cc',
      year: 2023,
      color: 'Red',
      features: ['Off-road Tires', 'Durable Frame']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike3'],
  },
  {
    id: 'bike4',
    shop_id: '2',
    name: 'Kawasaki KLX 150',
    description: 'Powerful dirt bike for adventure seekers, excellent off-road capability',
    category: 'dirt_bike',
    price_per_day: 700,
    price_per_week: 4500,
    price_per_month: 16000,
    is_available: false,
    specifications: {
      engine: '150cc',
      year: 2022,
      color: 'Blue',
      features: ['High Suspension', 'Disc Brakes', 'Trail Ready']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike4'],
  },
  {
    id: 'bike5',
    shop_id: '3',
    name: 'Honda Beat 115',
    description: 'Compact and fuel-efficient scooter, perfect for short trips',
    category: 'scooter',
    price_per_day: 300,
    price_per_week: 1800,
    price_per_month: 7000,
    is_available: true,
    specifications: {
      engine: '115cc',
      year: 2021,
      color: 'Green',
      features: ['Fuel Efficient', 'Easy to Handle']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike5'],
  },
  {
    id: 'bike6',
    shop_id: '3',
    name: 'Suzuki Raider 150',
    description: 'Sport bike with manual transmission, fast and responsive',
    category: 'sport_bike',
    price_per_day: 600,
    price_per_week: 3800,
    price_per_month: 14000,
    is_available: true,
    specifications: {
      engine: '150cc',
      year: 2023,
      color: 'Red/Black',
      features: ['6-Speed Manual', 'Sport Exhaust', 'Racing Design']
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: mockBikeImages['bike6'],
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: 'review1',
    shop_id: '1',
    vehicle_id: 'bike1',
    vehicle_type_id: '1',
    user_id: 'user1',
    rental_id: 'rental1',
    rating: 5,
    comment: 'Great scooter, very reliable and shop staff was super helpful!',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'review2',
    shop_id: '1',
    vehicle_id: 'bike2',
    vehicle_type_id: '1',
    user_id: 'user2',
    rental_id: 'rental2',
    rating: 4,
    comment: 'Good bike, would rent again. Just a bit expensive.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'review3',
    shop_id: '2',
    vehicle_id: 'bike3',
    vehicle_type_id: '1',
    user_id: 'user3',
    rental_id: 'rental3',
    rating: 5,
    comment: 'Perfect for exploring the island! The semi-auto was easy to use.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'review4',
    shop_id: '3',
    user_id: 'user4',
    rental_id: 'rental4',
    rating: 3,
    comment: 'Decent shop but the bikes need maintenance.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock users
export const mockUsers: User[] = [
  {
    id: 'user1',
    email: 'tourist1@example.com',
    first_name: 'John',
    last_name: 'Doe',
    phone_number: '+1 234 567 8901',
    role: 'tourist',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user2',
    email: 'tourist2@example.com',
    first_name: 'Jane',
    last_name: 'Smith',
    phone_number: '+1 234 567 8902',
    role: 'tourist',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'owner1',
    email: 'owner1@example.com',
    first_name: 'Mike',
    last_name: 'Johnson',
    phone_number: '+63 939 123 4567',
    role: 'shop_owner',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]; 